[package]
name = "exr2ultra-hdr"
version = "0.1.0"
edition = "2021"

[dependencies]
askama = "0.12.1"
clap = { version = "4.5.14", features = ["derive"] }
exr = "1.72.0"
jpeg-encoder = "0.6.0"
nalgebra = "0.33.0"
png = "0.17.13"
rcms = "0.1.0"
